services:
  app:
    build:
      context: .
      target: build
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/dist
    env_file:
      - .env
    command: ["npm", "run", "dev"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
